fix: upload website_build at CI_PROJECT_DIR regardless of PROJECT_ROOT and add file check-n

diff --git a/jobs/cargo_doc/cargo_doc.yml b/jobs/cargo_doc/cargo_doc.yml
--- a/jobs/cargo_doc/cargo_doc.yml
+++ b/jobs/cargo_doc/cargo_doc.yml
@@ -9,11 +9,18 @@ cargo_doc:
       ADDITIONAL_OPTIONS: ''
     script:
       - cd $PROJECT_ROOT
+      - if [ ! -f "Cargo.toml" ]; then
+      -   echo "ERROR --> Any Cargo.toml file isn't present in the given folder $PROJECT_ROOT"
+      -   exit 1
+      - fi
       - if [ ${ONLY_LIB} == "true" ]; then
       -   ADDITIONAL_OPTIONS+=" --lib"
       - fi
       - if [ ${RELEASE_MODE} == "true" ]; then
       -   ADDITIONAL_OPTIONS+=" --release"
+      - fi
+      - if [ ${CI_PROJECT_DIR} != ${PROJECT_ROOT} ]; then
+      -   OUTPUT_FOLDER="${CI_PROJECT_DIR}/${OUTPUT_FOLDER}"
       - fi
       - cargo doc --target-dir ${OUTPUT_FOLDER} $ADDITIONAL_OPTIONS
     artifacts:
@@ -21,4 +28,3 @@ cargo_doc:
       expose_as: "Cargo_doc build"
       paths:
         - $OUTPUT_FOLDER
-
